### ISSUE TITLE
PRACTICA_5

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo_tec#1]
[Practica_5_Fundamentos_Ingenieria_Software_1.pdf](https://github.com/user-attachments/files/17122254/Practica_5_Fundamentos_Ingenieria_Software_1.pdf)

**Comment by JORGELUIS2266** [comment]
20% DE 20% DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
